# Generated by Django 4.0.5 on 2022-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_c', models.CharField(max_length=200)),
                ('zon_hlv', models.CharField(max_length=200)),
                ('zon_mcls', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CopUBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.CharField(max_length=200)),
                ('rct_no', models.CharField(max_length=200)),
                ('cop_c', models.CharField(max_length=200)),
                ('chnl_dv', models.IntegerField()),
                ('de_dt_y', models.IntegerField()),
                ('de_dt_m', models.IntegerField()),
                ('de_dt_d', models.IntegerField()),
                ('vst_dt_y', models.IntegerField()),
                ('vst_dt_m', models.IntegerField()),
                ('vst_dt_d', models.IntegerField()),
                ('de_hr', models.IntegerField()),
                ('buy_am', models.IntegerField()),
                ('br_c', models.CharField(max_length=200)),
                ('zon_hlv', models.CharField(max_length=200)),
                ('zon_mcls', models.CharField(max_length=200)),
            ],
        ),
    ]
