# Generated by Django 3.2.12 on 2022-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('num_ex', models.IntegerField()),
                ('num_im', models.IntegerField()),
                ('amo_ex', models.IntegerField()),
                ('amo_im', models.IntegerField()),
                ('trade_b', models.IntegerField()),
                ('trade_pm', models.IntegerField()),
            ],
        ),
    ]
