# Generated by Django 3.2.7 on 2022-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='movies', to='movies.Movie'),
        ),
    ]
